### ISSUE TITLE
该模版在引用 Element 时产生错误

### ISSUE THREAD

**Issue by ss098** [ElementUI/element-in-laravel-starter#10]
通过该模版执行：

 - composer install
 - cnpm install
 - gulp watch

> Error when rendering component &lt;ElButton&gt;

在页面上不会显示任何内容，命令行会输出上面的错误。移除对于 Element UI 的引用，页面是一个可以正常执行的 Vue 页面。这个问题是今天（2016 年 12 月 13 日）所发生的，昨天没有这样的问题，在今天多次测试始终发生这样的问题。

**Comment by Abbotton** [comment]
我也遇到了同样的问题。自行安装laravel并单独引入ElementUI也不行。另外这个错误也出现在[element-starter](https://github.com/ElementUI/element-starter)

**Comment by Abbotton** [comment]
@ss098 请参考[这里][https://github.com/ElementUI/element-starter/issues/14]解决。

**Comment by ss098** [comment]
@Abbotton 感谢，我去看一下。
