### ISSUE TITLE
cross-env.js path in package.json

### ISSUE THREAD

**Issue by wonyeouuu** [ElementUI/element-in-laravel-starter#16]
I found that cross-env has updated their path to node_modules/cross-env/**dist**/bin/cross-env.js. 
We should modify the path in scripts in package.json and then run **npm run dev**.

**Comment by moxiaobei2** [comment]
how? I get the error:Cannot find module '/private/var/www/element-in-laravel-starter/node_modules/cross-env/bin/cross-env.js'

**Comment by wonyeouuu** [comment]
@moxiaobei2 add the '/dist' part in the scripts part of package.json file

**Comment by uran1980** [comment]
@see https://github.com/JeffreyWay/laravel-mix/issues/478#issuecomment-284191242

**Comment by Sliverwing** [comment]
#19 fixed this.

**Comment by adanwo** [comment]
From Windows:
Right clic over folder.
Git bash
npm run dev
