### ISSUE TITLE
Please add styles as scss also, so we can change theme 

### ISSUE THREAD

**Issue by saqueib** [ElementUI/element-in-laravel-starter#17]
It would be great if you can incorporate style and sass in this starter kit, currently its using bootstrap which is not ideal.

**In app.scss its importing default bootstrap and same is in _varaibles.scss** 

https://github.com/ElementUI/element-in-laravel-starter/blob/master/resources/assets/sass/app.scss

Thanks for great UI kit.

**Comment by csvwolf** [comment]
#22 is ok. Thank you.
