### ISSUE TITLE
fallbackLoader option has been deprecated - replace with "fallback"

### ISSUE THREAD

**Issue by yuzewang** [ElementUI/element-in-laravel-starter#18]
element-in-laravel-starter [master] ⚡ npm run dev

> @ dev /Users/yuze/work/yingdian/element-in-laravel-starter
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "public" is not an absolute path!

**Comment by Sidfate** [comment]
I have met the same problem，and I d't know how to fix it

**Comment by Sliverwing** [comment]
#19 update package.json may help you
