### ISSUE TITLE
gulp 以后报错

### ISSUE THREAD

**Issue by woodytang** [ElementUI/element-in-laravel-starter#2]
ERROR in ./resources/assets/js/App.vue
Module not found: Error: Can't resolve 'buble-loader' in '/Users/tangsi/Documents/新项目/vue-com/vue-com/resources/assets/js'
 @ ./resources/assets/js/App.vue 4:18-97
 @ ./resources/assets/js/app.js

ERROR in ./~/css-loader!./~/element-ui/lib/theme-default/index.css
Module not found: Error: Can't resolve 'url-loader?{"limit":10000,"name":"../fonts/[name].[hash:7].[ext]"}' in '/Users/tangsi/Documents/新项目/vue-com/vue-com'
 @ ./~/css-loader!./~/element-ui/lib/theme-default/index.css 6:810-859
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./resources/assets/js/app.js

ERROR in ./~/css-loader!./~/element-ui/lib/theme-default/index.css
Module not found: Error: Can't resolve 'url-loader?{"limit":10000,"name":"../fonts/[name].[hash:7].[ext]"}' in '/Users/tangsi/Documents/新项目/vue-com/vue-com'
 @ ./~/css-loader!./~/element-ui/lib/theme-default/index.css 6:873-923
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./resources/assets/js/app.js

ERROR in ./~/css-loader!./~/element-ui/lib/theme-default/index.css
Module not found: Error: Can't resolve 'url-loader?{"limit":10000,"name":"../fonts/[name].[hash:7].[ext]"}' in '/Users/tangsi/Documents/新项目/vue-com/vue-com'
 @ ./~/css-loader!./~/element-ui/lib/theme-default/index.css 6:952-1001
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./resources/assets/js/app.js

ERROR in ./~/css-loader!./~/element-ui/lib/theme-default/index.css
Module not found: Error: Can't resolve 'file-loader?{"limit":10000,"name":"../img/[name].[hash:7].[ext]"}' in '/Users/tangsi/Documents/新项目/vue-com/vue-com'
 @ ./~/css-loader!./~/element-ui/lib/theme-default/index.css 6:1034-1083
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./resources/assets/js/app.js

**Comment by csvwolf** [comment]
可以请问一下你克隆之后的操作步骤吗

**Comment by csvwolf** [comment]
如果没有问题那我就关了……
