### ISSUE TITLE
Switch back to official laravel-elixir-webpack-official

### ISSUE THREAD

**Issue by SebastianS90** [ElementUI/element-in-laravel-starter#7]
Please edit the `package.json` to use the official version again, my fix finally [got merged](https://github.com/JeffreyWay/laravel-elixir-webpack-official/commit/aa1ad29b6962306ca1c3ca3c2a8fa2e657f5133f):

`"laravel-elixir-webpack-official": "^1.0.10"`

**Comment by QingWei-Li** [comment]
PR welcome

**Comment by csvwolf** [comment]
@SebastianS90 Thank you for your contribution!
