### ISSUE TITLE
我要On demand import 组件，laravel这边怎么配置？

### ISSUE THREAD

**Issue by woodytang** [ElementUI/element-in-laravel-starter#9]
全部引入太大，如果要按需加载，laravel怎么配置呢？
文档上只讲了普通情况：
npm install babel-plugin-component -D

{
  "presets": [
    ["es2015", { "modules": false }]
  ],
  "plugins": [["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]]
}

这些在laravel怎么配？

**Comment by csvwolf** [comment]
参考：http://element.eleme.io/#/zh-CN/component/quickstart
